import React from 'react'
import {Email, Box, Item, Image, Span, A, renderEmail} from 'react-html-email'

const emailHtml = user =>
  renderEmail(
    <Email title="Your Nicebreakers report.">
      <Item>
        <Span fontSize={20}>{user.email}</Span>
      </Item>
      <Item>
        <Box
          cellSpacing={20}
          width="100%"
          style={{borderTop: '3px solid black'}}
        >
          <Item>
            <Span color="gray" lineHeight={20}>
              Generated by{' '}
              <A href="https://github.com/chromakode/react-html-email">
                react-html-email
              </A>
            </Span>
            <Image
              data-mc-bar="bar"
              data-mc-baz="baz"
              alt="react"
              src={user.imageUrl}
              width={100}
              height={100}
            />
            <A download="" href="">
              Source code
            </A>
          </Item>
        </Box>
      </Item>
    </Email>
  )

export const createEmails = userReports =>
  Object.values(userReports).map(user => ({
    to: user.email,
    html: emailHtml(user)
  }))
