module.exports = {
  REQUEST_NEXT_ROUND: 'REQUEST_NEXT_ROUND',
  START_EVENT: 'START_EVENT',
  ROOM: 'ROOM',
  EVENT_STARTED: 'EVENT_STARTED',
  EVENT_PREFIX: 'EVENT_',
  NEXT_ROUND: 'NEXT_ROUND',
  END_EVENT: 'END_EVENT',
  EVENT_ENDED: 'EVENT_ENDED',
  USER_JOINED_ROOM: 'USER_JOINED_ROOM',
  USER_JOINED: 'USER_JOINED',
  USER_LEFT_ROOM: 'USER_LEFT_ROOM',
  USER_LEFT: 'USER_LEFT'
}
