#!/usr/bin/env bash

# We want this entire script to exit if any single line fails.
set -e

# We trap any exit regardless of success and clean up the deploy branch.
function cleanup_at_exit {
  git checkout master
  git branch -D deploy
}

trap cleanup_at_exit EXIT

git checkout -b deploy # create branch for deployment
webpack -p # pack in production mode

git add -f public/bundle.js public/bundle.js.map # because we gitignore them...

git commit --allow-empty -m 'Deploying' # Commit...

git push --force heroku deploy:master # ... and deploy to heroku deployment branch.
